### ISSUE TITLE
BUG: Batch and epoch metrics under the test namespace are identical

### ISSUE THREAD

**Issue by Blaizzy** [neptune-ai/neptune-tensorflow-keras#23]
### Describe the bug
Batch and epoch metrics under the test namespace are identical

Example runs:
- Epoch metrics: https://app.neptune.ai/common/tf-keras-integration/e/TFK-39687/all?path=metrics%2Ftest%2Fepoch%2F
- Batch metrics: https://app.neptune.ai/common/tf-keras-integration/e/TFK-39687/all?path=metrics%2Ftest%2Fbatch%2F

### Reproduction
Here is a reproducible script:
https://colab.research.google.com/github/neptune-ai/examples/blob/master/integrations-and-supported-tools/tensorflow-keras/notebooks/Neptune_TensorFlow_Keras.ipynb

### Expected behaviour
Log precise metrics at epoch and batch levels.

**Comment by twolodzko** [comment]
We get those metrics from TensorFlow, so cannot fix this on our side. Maybe this should be clarified with TensorFlow developers?

**Comment by Blaizzy** [comment]
@twolodzko my bad actually. There is no bug.

I haven't touched TF issues since a few months ago and didn't prime my brain for this throwback

I ran a few experiments and found out I confused the two.
