### ISSUE TITLE
Tensorflow version specifier in setup.py

### ISSUE THREAD

**Issue by brainlykcz** [neptune-ai/neptune-tensorflow-keras#3]
Can you please set min version specifier for tensorflow in your `setup.py` - current setup is problematic for AWS sagemaker training jobs (and alike) - it attempts to install latest version of tensorflow and so disables GPU support for our training jobs - which is a showstopper :( 

for us `>=2.3.0` (and anyone who uses AWS sagemaker jobs) is crucial

**Comment by aniezurawski** [comment]
I think adding minimal version specifier to `setup.py` won't prevent from installing newest version if given package is not installed in environment. It will prevent `tensorflow` from upgrading only if it already is installed in specific version.

**Comment by brainlykcz** [comment]
you are right - our case is point (2) though where we already have 2.3.0 installed - we use `763104351884.dkr.ecr.eu-west-1.amazonaws.com/tensorflow-training:2.3.0-gpu-py37'` docker image from AWS and we want prevent neptune from installing tf 2.5.0 which unfortunately breaks GPU support :(

**Comment by aniezurawski** [comment]
If you already have `tensorflow` installed in any version then it won't not be upgraded since we do not require any specific version. Are sure you have `tensorflow` in you environemnt and not `tensorflow-gpu` which is different pip package?
Could you share result of `pip freeze` command?

@Herudaio should we drop `tensorflow` dependency from `setup.py` and verify presence of the library in runtime?

**Comment by brainlykcz** [comment]
hmm - this is what happens:

```
 3.8.6 ~/neptune-test >> docker run -it 763104351884.dkr.ecr.eu-west-1.amazonaws.com/tensorflow-training:2.3.0-gpu-py37 /bin/bash
root@8d594666ef46:/# pip install neptune-tensorflow-keras==0.9.1 
Collecting neptune-tensorflow-keras==0.9.1
  Downloading neptune-tensorflow-keras-0.9.1.tar.gz (8.7 kB)
Collecting neptune-client>=0.5.1
  Downloading neptune-client-0.9.15.tar.gz (237 kB)
     |████████████████████████████████| 237 kB 1.2 MB/s 
Collecting tensorflow
  Downloading tensorflow-2.5.0-cp37-cp37m-manylinux2010_x86_64.whl (454.3 MB)
     |██████                          | 85.0 MB 13.8 MB/s eta 0:00:27
```

**Comment by brainlykcz** [comment]
+ `pip freeze` from inside the container after installing `neptune-tensorflow-keras`

```
root@3b3ce9af53d7:/# pip freeze
absl-py==0.10.0
astunparse==1.6.3
attrs==21.2.0
awscli==1.18.142
bcrypt==3.2.0
boto3==1.15.1
botocore==1.18.1
bravado==11.0.3
bravado-core==5.17.0
cached-property==1.5.2
cachetools==4.1.1
certifi==2020.6.20
cffi==1.14.2
chardet==3.0.4
click==8.0.1
cloudpickle==1.6.0
colorama==0.4.3
cryptography==3.1
docutils==0.15.2
flatbuffers==1.12
future==0.18.2
gast==0.4.0
gevent==20.6.2
gitdb==4.0.7
GitPython==3.1.17
google-auth==1.21.2
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
greenlet==0.4.16
grpcio==1.34.1
h5py==3.1.0
horovod==0.19.5
idna==2.10
importlib-metadata==1.7.0
inotify-simple==1.2.1
jmespath==0.10.0
joblib==0.16.0
jsonpointer==2.1
jsonref==0.2
jsonschema==3.2.0
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
Markdown==3.2.2
monotonic==1.6
mpi4py==3.0.3
msgpack==1.0.2
neptune-client==0.9.15
neptune-tensorflow-keras==0.9.4
numpy==1.19.5
oauthlib==3.1.0
opencv-python==4.3.0.36
opt-einsum==3.3.0
packaging==20.4
pandas==1.1.0
paramiko==2.7.2
Pillow==7.2.0
protobuf==3.13.0
protobuf3-to-dict==0.1.5
psutil==5.7.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
PyJWT==2.1.0
PyNaCl==1.4.0
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
requests-oauthlib==1.3.0
retrying==1.3.3
rfc3987==1.3.8
rsa==4.5
s3transfer==0.3.3
sagemaker==1.72.0
sagemaker-experiments==0.1.24
sagemaker-tensorflow==2.3.0.1.0.0
sagemaker-tensorflow-training==20.1.2
sagemaker-training==3.6.2
scikit-learn==0.23.0
scipy==1.4.1
simplejson==3.17.2
six==1.15.0
sklearn==0.0
smdebug==0.9.3
smdebug-rulesconfig==0.1.4
smmap==4.0.0
strict-rfc3339==0.7
swagger-spec-validator==2.7.3
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.7.0
tensorflow==2.5.0
tensorflow-estimator==2.5.0
tensorflow-gpu @ https://aws-tensorflow-binaries.s3-us-west-2.amazonaws.com/tensorflow/r2.3_aws/20200902-124016/gpu/py37/tensorflow_gpu-2.3.0-cp37-cp37m-manylinux2010_x86_64.whl
termcolor==1.1.0
threadpoolctl==2.1.0
typing-extensions==3.7.4.3
urllib3==1.25.10
webcolors==1.11.1
websocket-client==1.0.1
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.1.0
zope.event==4.5.0
zope.interface==5.1.0
```

**Comment by aniezurawski** [comment]
Sorry, I should be more precise. Could you share your environment before installing? :)

**Comment by brainlykcz** [comment]
another update: 

``` brl470krk@brl470krk   3.8.6  ~/neptune-test  docker run -it 763104351884.dkr.ecr.eu-west-1.amazonaws.com/tensorflow-training:2.3.0-gpu-py37 /bin/bash
root@4be95a6080db:/# pip show tensorflow
WARNING: Package(s) not found: tensorflow
```

this image does not go with tensorflow installed at all - and you are right no version specified != latest and should trigger upgrade - it does install it because package was not there

**Comment by aniezurawski** [comment]
So, does installing `tensorflow` in desired version before installing `neptune-tensorflow-keras` resolves your issue?

**Comment by brainlykcz** [comment]
this may be a solution - let me try that :)

**Comment by aniezurawski** [comment]
I did some research and it won't work, I guess. `tensorflow` and `tensorflow-gpu` packages conflict. We should probably drop this dependency and check presence of the library in runtime.

**Comment by brainlykcz** [comment]
thanks a lot - this will help us :)

**Comment by brainlykcz** [comment]
kudos for quick response too :)

**Comment by aniezurawski** [comment]
As a temporary workaround you can use `--no-dependencies` switch for pip:
```
--no-deps, --no-dependencies
                        Ignore package dependencies
```

**Comment by Raalsky** [comment]
Hi @brainlykcz. We've drop the requirement of Tensorflow in the latest version of `neptune-tensorflow-keras` so you'll need to install it alongside with `tensorflow` or `tensorflow-gpu` itself. Let us know if you have any questions :wink:
