### ISSUE TITLE
BUG: doesn't work on newer macbooks running tensorflow-metal

### ISSUE THREAD

**Issue by brresnic** [neptune-ai/neptune-tensorflow-keras#48]
### Describe the bug
looks like this library doesn't work when running tensorflow-metal on m1 / m2 chips 

<img width="942" alt="Screenshot 2023-02-01 at 9 32 03 PM" src="https://user-images.githubusercontent.com/6865869/216224949-ca689824-7000-456e-a878-cfdb3ebae4c7.png">

```
**The operating system you're using:**
**The output of `python --version`:3.9
### Additional context
Add any other context about the problem here.

**Comment by Blaizzy** [comment]
Hi @brresnic 

Prince here,

Could you share a minimal reproducible code?

**Comment by SiddhantSadangi** [comment]
Hello @brresnic ,
Just checking if you still need help with this.
