### ISSUE TITLE
NPT13169:  `neptune_client` still a dependency in > 2.0.1 on conda-forge

### ISSUE THREAD

**Issue by lesimppa** [neptune-ai/neptune-tensorflow-keras#56]
### Describe the bug
Hi all. Thanks for the package.  I've made the transition from `neptune_client` to `neptune` as the client is being deprecated.  Based on my understanding of `2.0.1`, `neptune_client` shouldn't be a dependency anymore and be replaced by `neptune`. It seems that it's not reflected in the conda package.

Am I missing something?

### Reproduction
```
> conda search -c conda-forge neptune-tensorflow-keras --info
neptune-tensorflow-keras 2.0.0 pyhd8ed1ab_0
-------------------------------------------
file name   : neptune-tensorflow-keras-2.0.0-pyhd8ed1ab_0.conda
name        : neptune-tensorflow-keras
version     : 2.0.0
build       : pyhd8ed1ab_0
build number: 0
size        : 16 KB
license     : Apache-2.0
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/neptune-tensorflow-keras-2.0.0-pyhd8ed1ab_0.conda
md5         : 7bedfeffd2eea105786112d17c0c63a6
timestamp   : 2023-02-06 12:12:48 UTC
dependencies:
  - neptune-client >=0.9
  - python >=3.6
  - tensorflow >=2,<3


neptune-tensorflow-keras 2.1.0 pyhd8ed1ab_0
-------------------------------------------
file name   : neptune-tensorflow-keras-2.1.0-pyhd8ed1ab_0.conda
name        : neptune-tensorflow-keras
version     : 2.1.0
build       : pyhd8ed1ab_0
build number: 0
size        : 17 KB
license     : Apache-2.0
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/neptune-tensorflow-keras-2.1.0-pyhd8ed1ab_0.conda
md5         : bf45fe8e0853107dc0bb55602e7ae435
timestamp   : 2023-03-13 11:26:14 UTC
dependencies:
  - neptune-client >=0.9
  - python >=3.6
  - tensorflow >=2,<3


neptune-tensorflow-keras 2.1.1 pyhd8ed1ab_0
-------------------------------------------
file name   : neptune-tensorflow-keras-2.1.1-pyhd8ed1ab_0.conda
name        : neptune-tensorflow-keras
version     : 2.1.1
build       : pyhd8ed1ab_0
build number: 0
size        : 17 KB
license     : Apache-2.0
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/neptune-tensorflow-keras-2.1.1-pyhd8ed1ab_0.conda
md5         : 3cc66a789ca53008bb622ec80ea38a41
timestamp   : 2023-03-31 16:41:01 UTC
dependencies:
  - neptune-client >=0.9
  - python >=3.6
  - tensorflow >=2,<3

```
### Expected behavior
`neptune-client` being replaced by `neptune` in dependencies for > 2.0.1

**Comment by SiddhantSadangi** [comment]
Hello @lesimppa ,
Thanks for bringing this to our attention! 
I have forwarded this to our dev team and will get it fixed. I will keep you updated on the status here.

Meanwhile, if this is a blocker for you, can you install the package from pip?
`pip install neptune-tensorflow-keras`

This does not have `neptune-client` as a dependency.

Also, please don't hesitate to reach out in case you have any other queries/feedback!

**Comment by lesimppa** [comment]
Hi @SiddhantSadangi,

Thank you for looking into this.  We aren't blocked so I'll wait for the conda release 👍

**Comment by johnczontos** [comment]
I am blocked by this bug.  When will this be updated for conda?

**Comment by SiddhantSadangi** [comment]
Hello @lesimppa and @johnczontos ,
Sorry for the delay here. I've contacted the dev team again and will update you on the ETA.

Meanwhile, @johnczontos, is downloading the package from pip a viable option for you?

**Comment by johnczontos** [comment]
This is still not working for me, even with pip.
looks like `pip install neptune-tensorflow-keras` still installs neptune-client.
![Screenshot 2023-05-04 at 2 58 36 PM](https://user-images.githubusercontent.com/32498952/236338798-b125d379-ee40-4691-b341-5ff126d82b2f.png)

**Comment by johnczontos** [comment]
I am working on my institutions high-performance cluster and it has very old frozen versions of python and pip.  I will keep trying to get a virtualenv with on updated version of pyton running but it's a pain.  If you have any tips let me know.  I usually work in conda enviroments on this server.

**Comment by SiddhantSadangi** [comment]
Can you share the python, pip, and neptune-client versions you are using?

On conda, you can try the below steps:

1. Install `neptune-tensorflow-keras`
2. Uninstall `neptune` and `neptune-client`
3. Reinstall `neptune`

This should get the `neptune-tensorflow-keras` integration running. I know its a couple of extra steps, sorry for that :(

**Comment by SiddhantSadangi** [comment]
Hey @lesimppa , @johnczontos 👋 

We have finally updated our conda package to remove `neptune-client` as a dependency 🚀 

This change will be visible from `neptune-tensorflow-keras v2.2.2` onwards:

```
neptune-tensorflow-keras 2.2.2 pyhd8ed1ab_0
-------------------------------------------
file name   : neptune-tensorflow-keras-2.2.2-pyhd8ed1ab_0.conda
name        : neptune-tensorflow-keras
version     : 2.2.2
build       : pyhd8ed1ab_0
build number: 0
size        : 17 KB
license     : Apache-2.0
subdir      : noarch
url         : https://conda.anaconda.org/conda-forge/noarch/neptune-tensorflow-keras-2.2.2-pyhd8ed1ab_0.conda
md5         : 71fa399c17ef4b3b0475843ba69f99cc
timestamp   : 2024-05-14 11:05:49 UTC
dependencies: 
  - neptune >=1.0.0
  - python >=3.6
  - tensorflow >=2,<3
```

Closing this thread now, but please feel free to reach out if you need any further support 🤗
